version: 1
services:
- type: web
  name: drl
  runtime: docker
  repo: https://github.com/eggplants/dlsite-recommendation-llm
  region: singapore
  plan: free
  branch: master
  dockerfilePath: ./Dockerfile
  dockerContext: .
  numInstances: 1
  healthCheckPath: /
  domains:
  - drl.egpl.dev
  envVars:
  - key: PINECONE_API_KEY
    sync: false
  - key: PINECONE_INDEX
    value: dlsite-recommendation-llm
  - key: PINECONE_ENV
    value: gcp-starter
  - key: OPENAI_API_KEY
    sync: false
  - key: OPENAI_API_MODEL
    value: gpt-3.5-turbo
  - key: OPENAI_API_TEMPERATURE
    value: '0.5'
